# Tensors (张量)
Tensors 类似于 NumPy 的 ndarrays ，同时 Tensors 可以使用 GPU 进行计算。

In [11]:
from __future__ import print_function
import torch

In [12]:
# 构造一个5x3矩阵，不初始化。
x = torch.empty(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [13]:
# 构造一个随机初始化的矩阵：
x = torch.rand(5,3)
print(x)

tensor([[0.4833, 0.7849, 0.4319],
        [0.4646, 0.4915, 0.6638],
        [0.6432, 0.1048, 0.8633],
        [0.4732, 0.4428, 0.8005],
        [0.0137, 0.3517, 0.3389]])


In [14]:
# 构造一个矩阵全为 0，而且数据类型是 long.
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [15]:
# 构造一个张量，直接使用数据
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [17]:
# 创建一个 tensor 基于已经存在的 tensor
x = x.new_ones(5,3,dtype=torch.double)
print(x)

x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.1398, 0.7834, 0.4348],
        [0.0973, 0.1944, 0.0866],
        [0.9140, 0.2526, 0.0718],
        [0.5142, 0.8575, 0.4582],
        [0.7659, 0.8900, 0.5748]])


In [20]:
# 获取它的维度信息
print(x.size())

torch.Size([5, 3])


In [21]:
# torch.Size 是一个元组，所以它支持左右的元组操作。

# 加法操作

In [22]:
# 加法方式一：
y = torch.rand(5, 3)
print(x + y)

tensor([[0.7108, 1.4392, 1.1150],
        [0.5464, 0.6898, 0.1647],
        [1.2776, 0.3491, 0.5928],
        [1.2971, 1.6859, 1.1811],
        [1.2300, 1.1283, 1.5063]])


In [23]:
# 加法方式二：
print(torch.add(x, y))

tensor([[0.7108, 1.4392, 1.1150],
        [0.5464, 0.6898, 0.1647],
        [1.2776, 0.3491, 0.5928],
        [1.2971, 1.6859, 1.1811],
        [1.2300, 1.1283, 1.5063]])


In [24]:
# 加法: 提供一个输出 tensor 作为参数
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.7108, 1.4392, 1.1150],
        [0.5464, 0.6898, 0.1647],
        [1.2776, 0.3491, 0.5928],
        [1.2971, 1.6859, 1.1811],
        [1.2300, 1.1283, 1.5063]])


In [25]:
# 加法: in-place
y.add_(x)
print(y)

tensor([[0.7108, 1.4392, 1.1150],
        [0.5464, 0.6898, 0.1647],
        [1.2776, 0.3491, 0.5928],
        [1.2971, 1.6859, 1.1811],
        [1.2300, 1.1283, 1.5063]])


In [26]:
# 注意 任何使张量会发生变化的操作都有一个前缀 '_'

In [27]:
# 使用标准的  NumPy 类似的索引操作
print(x[:, 1])

tensor([0.7834, 0.1944, 0.2526, 0.8575, 0.8900])


In [29]:
# 改变大小：如果你想改变一个 tensor 的大小或者形状，你可以使用 torch.view

x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1,8)  # the size -1 is inferred from other dimensions
print(x.size())
print(y.size())
print(z.size())

torch.Size([4, 4])
torch.Size([16])
torch.Size([2, 8])


In [31]:
# 如果你有一个元素 tensor ，使用 .item() 来获得这个 value
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.1646])
-1.16457200050354
